# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160922_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.TextField(default=datetime.datetime(2016, 9, 22, 10, 44, 2, 494000, tzinfo=utc)),
        ),
    ]
