# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160922_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(default=datetime.datetime(2016, 9, 22, 10, 47, 52, 780000, tzinfo=utc), max_length=120),
        ),
    ]
