# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160922_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(default=datetime.datetime(2016, 9, 22, 11, 11, 25, 812000, tzinfo=utc), max_length=15),
        ),
    ]
