# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160922_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='pub',
            field=models.DateField(default=datetime.datetime(2016, 9, 22, 11, 16, 6, 325000, tzinfo=utc)),
        ),
    ]
