# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20160922_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub',
            field=models.DateField(default=datetime.datetime(2016, 9, 22, 11, 31, 38, 121000, tzinfo=utc)),
        ),
    ]
