# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20160922_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub',
            field=models.DateField(),
        ),
    ]
